name: Build on PR
'on': pull_request

jobs:
  static_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if raw Markdown compiler is not used.
        run: bash ./misc/check-raw-md.bash

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install deps and generate a site
        env:
          FB_APIKEY: ${{ secrets.FB_APIKEY}}
          FB_AUTHDOMAIN: ${{ secrets.FB_AUTHDOMAIN}}
          FB_PROJECTID: ${{ secrets.FB_PROJECTID }}
          FB_STORAGEBUCKET: ${{ secrets.FB_STORAGEBUCKET }}
          FB_MESSAGINGSENDERID: ${{ secrets.FB_MESSAGINGSENDERID }}
          FB_APPID: ${{ secrets.FB_APPID }}
          FB_MEASUREMENTID: ${{ secrets.FB_MEASUREMENTID }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
        run: npm ci && npm run build

      - name: Add CSP meta tag
        run: python3 ./misc/set-csp.py
