name: Deploy to Firebase Hosting on PR
'on': pull_request

jobs:
  static_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if raw Markdown compiler is not used.
        run: bash ./misc/check-raw-md.bash

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install deps and generate a site
        env:
          FB_APIKEY: ${{ secrets.FB_APIKEY}}
          FB_AUTHDOMAIN: ${{ secrets.FB_AUTHDOMAIN}}
          FB_PROJECTID: ${{ secrets.FB_PROJECTID }}
          FB_STORAGEBUCKET: ${{ secrets.FB_STORAGEBUCKET }}
          FB_MESSAGINGSENDERID: ${{ secrets.FB_MESSAGINGSENDERID }}
          FB_APPID: ${{ secrets.FB_APPID }}
          FB_MEASUREMENTID: ${{ secrets.FB_MEASUREMENTID }}
        run: npm ci && npm run build

      - name: Add CSP meta tag
        run: python3 ./misc/set-csp.py

      - name: Deploy hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WYWIWYA }}'
          channelId: live
          projectId: wywiwya


  deploy-firestore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy firebase rules
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules -f
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WYWIWYA }}

      - name: Deploy firebase indexes
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:indexes -f
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WYWIWYA }}

  deploy-firebase-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install deps
        run: npm ci && npm -w functions ci

      - name: lint and build
        env:
          FB_APIKEY: ${{ secrets.FB_APIKEY}}
          FB_AUTHDOMAIN: ${{ secrets.FB_AUTHDOMAIN}}
          FB_PROJECTID: ${{ secrets.FB_PROJECTID }}
          FB_STORAGEBUCKET: ${{ secrets.FB_STORAGEBUCKET }}
          FB_MESSAGINGSENDERID: ${{ secrets.FB_MESSAGINGSENDERID }}
          FB_APPID: ${{ secrets.FB_APPID }}
          FB_MEASUREMENTID: ${{ secrets.FB_MEASUREMENTID }}
        run: npm -w functions run build

      - name: Deploy functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions -f
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WYWIWYA }}

